# Site settings
title: Andrew Krug's Musings
email: andrewkrug@gmail.com
description: "Security, Linux, and other blog musings by Andrew Krug.  Now with extra markdown awesome. :)"
baseurl: ""
url: "http://andrewkrug.github.io"
twitter_username: andrewkrug
github_username:  andrewkrug

# Build settings
markdown: redcarpet
permalink: pretty
