# Site settings
title: Andrew Krug's Musings
email: andrewkrug@gmail.com
description: "Security, Linux, and other musings by Andrew Krug."
baseurl: ""
url: "http://andrewkrug.github.io"
twitter_username: andrewkrug
github_username:  andrewkrug

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

# Build settings
markdown: kramdown
permalink: pretty

#Rake Generator
post:
  template: _template/_post.txt
  extension: md
page:
  template: _template/_page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/

  #Add bootstrap SASS support

  sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
